<?php

$config = [
	'widgets'    => [
		'general-elements' => [
			'title'    => __( 'General Widgets', 'designbox-builder' ),
			'elements' => [
				'image-box'         => [
					'label'        => esc_html__( 'Image Box', 'designbox-builder' ),
					'is_pro'       => false,
					'is_extension' => false,
					'is_upcoming'  => false,
					'demo_url'     => '',
					'doc_url'      => 'https://support.wpdesignbox.com/docs/wdb/widgets/wdb-widgets/wdb-image-box/',
					'youtube_url'  => '',
				],
				'image-box-slider'  => [
					'label'        => esc_html__( 'Image Box Slider', 'designbox-builder' ),
					'is_pro'       => false,
					'is_extension' => false,
					'is_upcoming'  => false,
					'demo_url'     => '',
					'doc_url'      => 'https://support.wpdesignbox.com/docs/wdb/widgets/wdb-widgets/wdb-image-box-slider/',
					'youtube_url'  => '',
				],
				'typewriter'        => [
					'label'        => esc_html__( 'Typewriter', 'designbox-builder' ),
					'is_pro'       => false,
					'is_extension' => false,
					'is_upcoming'  => false,
					'demo_url'     => '',
					'doc_url'      => 'https://support.wpdesignbox.com/docs/wdb/widgets/wdb-widgets/wdb-typewriter/',
					'youtube_url'  => '',
				],
				'animated-title'    => [
					'label'        => esc_html__( 'Animated Title', 'designbox-builder' ),
					'is_pro'       => false,
					'is_extension' => false,
					'is_upcoming'  => false,
					'demo_url'     => '',
					'doc_url'      => 'https://support.wpdesignbox.com/docs/wdb/widgets/wdb-widgets/wdb-animated-title/',
					'youtube_url'  => '',
				],
				'animated-text'     => [
					'label'        => esc_html__( 'Animated Text', 'designbox-builder' ),
					'is_pro'       => false,
					'is_extension' => false,
					'is_upcoming'  => false,
					'demo_url'     => '',
					'doc_url'      => 'https://support.wpdesignbox.com/docs/wdb/widgets/wdb-widgets/wdb-animated-text/',
					'youtube_url'  => '',
				],
				'social-icons'      => [
					'label'        => esc_html__( 'Social Icons', 'designbox-builder' ),
					'is_pro'       => false,
					'is_extension' => false,
					'is_upcoming'  => false,
					'demo_url'     => '',
					'doc_url'      => 'https://support.wpdesignbox.com/docs/wdb/widgets/wdb-widgets/wdb-social-icons/',
					'youtube_url'  => '',
				],
				'image'             => [
					'label'        => esc_html__( 'Image', 'designbox-builder' ),
					'is_pro'       => false,
					'is_extension' => false,
					'is_upcoming'  => false,
					'demo_url'     => '',
					'doc_url'      => 'https://support.wpdesignbox.com/docs/wdb/widgets/wdb-widgets/wdb-image/',
					'youtube_url'  => '',
				],
				'image-gallery'     => [
					'label'        => esc_html__( 'Image Gallery', 'designbox-builder' ),
					'is_pro'       => false,
					'is_extension' => false,
					'is_upcoming'  => false,
					'demo_url'     => '',
					'doc_url'      => 'https://support.wpdesignbox.com/docs/wdb/widgets/wdb-widgets/wdb-image-gallery/',
					'youtube_url'  => '',
				],
				'text-hover-image'  => [
					'label'        => esc_html__( 'Text Hover Image', 'designbox-builder' ),
					'is_pro'       => false,
					'is_extension' => false,
					'is_upcoming'  => false,
					'demo_url'     => '',
					'doc_url'      => 'https://support.wpdesignbox.com/docs/wdb/widgets/wdb-widgets/wdb-text-hover-image/',
					'youtube_url'  => '',
				],
				'brand-slider'      => [
					'label'        => esc_html__( 'Brand Slider', 'designbox-builder' ),
					'is_pro'       => false,
					'is_extension' => false,
					'is_upcoming'  => false,
					'demo_url'     => '',
					'doc_url'      => 'https://support.wpdesignbox.com/docs/wdb/widgets/wdb-widgets/wdb-brand-slider/',
					'youtube_url'  => '',
				],
				'counter'           => [
					'label'        => esc_html__( 'Counter', 'designbox-builder' ),
					'is_pro'       => false,
					'is_extension' => false,
					'is_upcoming'  => false,
					'demo_url'     => '',
					'doc_url'      => 'https://support.wpdesignbox.com/docs/wdb/widgets/wdb-widgets/wdb-counter/',
					'youtube_url'  => '',
				],
				'icon-box'          => [
					'label'        => esc_html__( 'Icon Box', 'designbox-builder' ),
					'is_pro'       => false,
					'is_extension' => false,
					'is_upcoming'  => false,
					'demo_url'     => '',
					'doc_url'      => 'https://support.wpdesignbox.com/docs/wdb/widgets/wdb-widgets/wdb-icon-box/',
					'youtube_url'  => '',
				],
				'testimonial'       => [
					'label'        => esc_html__( 'Testimonial', 'designbox-builder' ),
					'is_pro'       => false,
					'is_extension' => false,
					'is_upcoming'  => false,
					'demo_url'     => '',
					'doc_url'      => 'https://support.wpdesignbox.com/docs/wdb/widgets/wdb-widgets/wdb-testimonial/',
					'youtube_url'  => '',
				],
				'testimonial2'      => [
					'label'        => esc_html__( 'Testimonial 2', 'designbox-builder' ),
					'is_pro'       => false,
					'is_extension' => false,
					'is_upcoming'  => false,
					'demo_url'     => '',
					'doc_url'      => 'https://support.wpdesignbox.com/docs/wdb/widgets/wdb-widgets/wdb-testimonial-2/',
					'youtube_url'  => '',
				],
				'testimonial3'      => [
					'label'        => esc_html__( 'Testimonial 3', 'designbox-builder' ),
					'is_pro'       => false,
					'is_extension' => false,
					'is_upcoming'  => false,
					'demo_url'     => '',
					'doc_url'      => 'https://support.wpdesignbox.com/docs/wdb/widgets/wdb-widgets/wdb-testimonial-3/',
					'youtube_url'  => '',
				],
				'button'            => [
					'label'        => esc_html__( 'Button', 'designbox-builder' ),
					'is_pro'       => false,
					'is_extension' => false,
					'is_upcoming'  => false,
					'demo_url'     => '',
					'doc_url'      => 'https://support.wpdesignbox.com/docs/wdb/widgets/wdb-widgets/wdb-button/',
					'youtube_url'  => '',
				],
				'image-compare'     => [
					'label'        => esc_html__( 'Image Compare', 'designbox-builder' ),
					'is_pro'       => false,
					'is_extension' => false,
					'is_upcoming'  => false,
					'demo_url'     => '',
					'doc_url'      => 'https://support.wpdesignbox.com/docs/wdb/widgets/wdb-widgets/wdb-image-compare/',
					'youtube_url'  => '',
				],
				'progressbar'       => [
					'label'        => esc_html__( 'Progressbar', 'designbox-builder' ),
					'is_pro'       => false,
					'is_extension' => false,
					'is_upcoming'  => false,
					'demo_url'     => '',
					'doc_url'      => 'https://support.wpdesignbox.com/docs/wdb/widgets/wdb-widgets/wdb-progressbar/',
					'youtube_url'  => '',
				],
				'team'              => [
					'label'        => esc_html__( 'Team', 'designbox-builder' ),
					'is_pro'       => false,
					'is_extension' => false,
					'is_upcoming'  => false,
					'demo_url'     => '',
					'doc_url'      => 'https://support.wpdesignbox.com/docs/wdb/widgets/wdb-widgets/wdb-team/',
					'youtube_url'  => '',
				],
				'one-page-nav'      => [
					'label'        => esc_html__( 'One Page Nav', 'designbox-builder' ),
					'is_pro'       => false,
					'is_extension' => false,
					'is_upcoming'  => false,
					'demo_url'     => '',
					'doc_url'      => 'https://support.wpdesignbox.com/docs/wdb/widgets/wdb-widgets/wdb-one-page-nav/',
					'youtube_url'  => '',
				],
				'timeline'          => [
					'label'        => esc_html__( 'Timeline', 'designbox-builder' ),
					'is_pro'       => false,
					'is_extension' => false,
					'is_upcoming'  => false,
					'demo_url'     => '',
					'doc_url'      => 'https://support.wpdesignbox.com/docs/wdb/widgets/wdb-widgets/wdb-timeline/',
					'youtube_url'  => '',
				],
				'tabs'              => [
					'label'        => esc_html__( 'Tabs', 'designbox-builder' ),
					'is_pro'       => false,
					'is_extension' => false,
					'is_upcoming'  => false,
					'demo_url'     => '',
					'doc_url'      => 'https://support.wpdesignbox.com/docs/wdb/widgets/wdb-widgets/wdb-tabs/',
					'youtube_url'  => '',
				],
				'services-tab'      => [
					'label'        => esc_html__( 'Services Tabs', 'designbox-builder' ),
					'is_pro'       => false,
					'is_extension' => false,
					'is_upcoming'  => false,
					'demo_url'     => '',
					'doc_url'      => 'https://support.wpdesignbox.com/docs/wdb/widgets/wdb-widgets/wdb-services-tab/',
					'youtube_url'  => '',
				],
				'floating-elements' => [
					'label'        => esc_html__( 'Floating Elements', 'designbox-builder' ),
					'is_pro'       => false,
					'is_extension' => false,
					'is_upcoming'  => false,
					'demo_url'     => '',
					'doc_url'      => 'https://support.wpdesignbox.com/docs/wdb/widgets/wdb-widgets/wdb-floating-elements/',
					'youtube_url'  => '',
				],
				'event-slider'      => [
					'label'        => esc_html__( 'Event Slider', 'designbox-builder' ),
					'is_pro'       => false,
					'is_extension' => false,
					'is_upcoming'  => false,
					'demo_url'     => '',
					'doc_url'      => 'https://support.wpdesignbox.com/docs/wdb/widgets/wdb-widgets/wdb-event-slider/',
					'youtube_url'  => '',
				],
				'content-slider'    => [
					'label'        => esc_html__( 'Content Slider', 'designbox-builder' ),
					'is_pro'       => false,
					'is_extension' => false,
					'is_upcoming'  => false,
					'demo_url'     => '',
					'doc_url'      => 'https://support.wpdesignbox.com/docs/wdb/widgets/wdb-widgets/wdb-content-slider/',
					'youtube_url'  => '',
				],
				'countdown'         => [
					'label'        => esc_html__( 'Countdown', 'designbox-builder' ),
					'is_pro'       => false,
					'is_extension' => false,
					'is_upcoming'  => false,
					'demo_url'     => '',
					'doc_url'      => 'https://support.wpdesignbox.com/docs/wdb/widgets/wdb-widgets/wdb-countdown/',
					'youtube_url'  => '',
				],
				'animated-heading'  => [
					'label'       => esc_html__( 'Animated Heading', 'designbox-builder' ),
					'is_pro'       => false,
					'is_extension' => false,
					'is_upcoming'  => false,
					'demo_url'     => '',
					'doc_url'      => 'https://support.wpdesignbox.com/docs/wdb/widgets/wdb-widgets/wdb-animated-heading/',
					'youtube_url'  => '',
				],
			]
		],
		'hf-elements'      => [
			'title'    => __( 'Header/Footer Widgets', 'designbox-builder' ),
			'elements' => [
				'site-logo' => [
					'label'        => esc_html__( 'Site Logo', 'designbox-builder' ),
					'is_pro'       => false,
					'is_extension' => false,
					'is_upcoming'  => false,
					'demo_url'     => '',
					'doc_url'      => '',
					'youtube_url'  => '',
				],
				'nav-menu'  => [
					'label'        => esc_html__( 'Nav Menu', 'designbox-builder' ),
					'is_pro'       => false,
					'is_extension' => false,
					'is_upcoming'  => false,
					'demo_url'     => '',
					'doc_url'      => '',
					'youtube_url'  => '',
				],
			]
		],
		'dynamic-elements' => [
			'title'    => __( 'Dynamic Widgets', 'designbox-builder' ),
			'elements' => [
				'post-title'         => [
					'label'        => esc_html__( 'Post Title', 'designbox-builder' ),
					'is_pro'       => false,
					'is_extension' => false,
					'is_upcoming'  => false,
					'demo_url'     => '',
					'doc_url'      => '',
					'youtube_url'  => '',
				],
				'post-feature-image' => [
					'label'        => esc_html__( 'Post Feature Image', 'designbox-builder' ),
					'is_pro'       => false,
					'is_extension' => false,
					'is_upcoming'  => false,
					'demo_url'     => '',
					'doc_url'      => '',
					'youtube_url'  => '',
				],
				'post-excerpt'       => [
					'label'        => esc_html__( 'Post Excerpt', 'designbox-builder' ),
					'is_pro'       => false,
					'is_extension' => false,
					'is_upcoming'  => false,
					'demo_url'     => '',
					'doc_url'      => '',
					'youtube_url'  => '',
				],
				'post-content'       => [
					'label'        => esc_html__( 'Post Content', 'designbox-builder' ),
					'is_pro'       => false,
					'is_extension' => false,
					'is_upcoming'  => false,
					'demo_url'     => '',
					'doc_url'      => '',
					'youtube_url'  => '',
				],
				'post-comment'       => [
					'label'        => esc_html__( 'Post Comment', 'designbox-builder' ),
					'is_pro'       => false,
					'is_extension' => false,
					'is_upcoming'  => false,
					'demo_url'     => '',
					'doc_url'      => '',
					'youtube_url'  => '',
				],
				'post-meta-info'     => [
					'label'        => esc_html__( 'Post Meta Info', 'designbox-builder' ),
					'is_pro'       => false,
					'is_extension' => false,
					'is_upcoming'  => false,
					'demo_url'     => '',
					'doc_url'      => '',
					'youtube_url'  => '',
				],
				'post-paginate'      => [
					'label'        => esc_html__( 'Post Paginate', 'designbox-builder' ),
					'is_pro'       => false,
					'is_extension' => false,
					'is_upcoming'  => false,
					'demo_url'     => '',
					'doc_url'      => '',
					'youtube_url'  => '',
				],
				'post-social-share'  => [
					'label'        => esc_html__( 'Post Social Share', 'designbox-builder' ),
					'is_pro'       => false,
					'is_extension' => false,
					'is_upcoming'  => false,
					'demo_url'     => '',
					'doc_url'      => '',
					'youtube_url'  => '',
				],
				'posts'              => [
					'label'        => esc_html__( 'Posts', 'designbox-builder' ),
					'is_pro'       => false,
					'is_extension' => false,
					'is_upcoming'  => false,
					'demo_url'     => '',
					'doc_url'      => 'https://support.wpdesignbox.com/docs/wdb/widgets/wdb-widgets/wdb-posts/',
					'youtube_url'  => '',
				],
				'archive-title'      => [
					'label'        => esc_html__( 'Archive Title', 'designbox-builder' ),
					'is_pro'       => false,
					'is_extension' => false,
					'is_upcoming'  => false,
					'demo_url'     => '',
					'doc_url'      => '',
					'youtube_url'  => '',
				],
				'portfolio'          => [
					'label'        => __( 'Portfolio', 'designbox-builder' ),
					'is_pro'       => false,
					'is_extension' => true,
					'is_upcoming'  => false,
					'demo_url'     => '',
					'doc_url'      => 'https://support.wpdesignbox.com/docs/wdb/widgets/wdb-widgets/wdb-portfolio/',
					'youtube_url'  => '',
				],
				'search-form'        => [
					'label'        => __( 'Search Form', 'designbox-builder' ),
					'is_pro'       => false,
					'is_extension' => false,
					'is_upcoming'  => false,
					'demo_url'     => '',
					'doc_url'      => '',
					'youtube_url'  => '',
				],
				'search-query'       => [
					'label'        => __( 'Search Query', 'designbox-builder' ),
					'is_pro'       => false,
					'is_extension' => false,
					'is_upcoming'  => false,
					'demo_url'     => '',
					'doc_url'      => '',
					'youtube_url'  => '',
				],
				'search-no-result'   => [
					'label'        => __( 'Search No Result', 'designbox-builder' ),
					'is_pro'       => false,
					'is_extension' => false,
					'is_upcoming'  => false,
					'demo_url'     => '',
					'doc_url'      => '',
					'youtube_url'  => '',
				],
			]
		],
		'form-elements'    => [
			'title'    => __( 'Form Widgets', 'designbox-builder' ),
			'elements' => [
				'contact-form-7' => [
					'label'        => esc_html__( 'Contact Form 7', 'designbox-builder' ),
					'is_pro'       => false,
					'is_extension' => false,
					'is_upcoming'  => false,
					'demo_url'     => '',
					'doc_url'      => 'https://support.wpdesignbox.com/docs/wdb/widgets/wdb-widgets/wdb-contact-form-7/',
					'youtube_url'  => '',
				],
				'mailchimp'      => [
					'label'        => esc_html__( 'Mailchimp', 'designbox-builder' ),
					'is_pro'       => false,
					'is_extension' => true,
					'is_upcoming'  => false,
					'demo_url'     => '',
					'doc_url'      => 'https://support.wpdesignbox.com/docs/wdb/widgets/wdb-widgets/wdb-mailchimp/',
					'youtube_url'  => '',
				],
			]
		],
		'video-elements'   => [
			'title'    => __( 'Video Widgets', 'designbox-builder' ),
			'elements' => [
				'video-popup'      => [
					'label'        => __( 'Video Popup', 'designbox-builder' ),
					'is_pro'       => false,
					'is_extension' => true,
					'is_upcoming'  => false,
					'demo_url'     => '',
					'doc_url'      => 'https://support.wpdesignbox.com/docs/wdb/widgets/wdb-widgets/wdb-video-popup/',
					'youtube_url'  => '',
				],
				'video-box'        => [
					'label'        => __( 'Video Box', 'designbox-builder' ),
					'is_pro'       => false,
					'is_extension' => true,
					'is_upcoming'  => false,
					'demo_url'     => '',
					'doc_url'      => 'https://support.wpdesignbox.com/docs/wdb/widgets/wdb-widgets/wdb-video-box/',
					'youtube_url'  => '',
				],
				'video-box-slider' => [
					'label'        => __( 'Video Box Slider', 'designbox-builder' ),
					'is_pro'       => false,
					'is_extension' => true,
					'is_upcoming'  => false,
					'demo_url'     => '',
					'doc_url'      => 'https://support.wpdesignbox.com/docs/wdb/widgets/wdb-widgets/wdb-video-box-slider/',
					'youtube_url'  => '',
				],
				'video-mask'       => [
					'label'        => __( 'Video Mask', 'designbox-builder' ),
					'is_pro'       => false,
					'is_extension' => true,
					'is_upcoming'  => false,
					'demo_url'     => '',
					'doc_url'      => 'https://support.wpdesignbox.com/docs/wdb/widgets/wdb-widgets/wdb-video-mask/',
					'youtube_url'  => '',
				],
			]
		],
	],
	'extensions' => [
		'general-extensions' => [
			'title'    => __( 'General Extension', 'designbox-builder' ),
			'elements' => [
				'custom-css' => [
					'label'        => esc_html__( 'Custom CSS', 'designbox-builder' ),
					'is_pro'       => false,
					'is_extension' => false,
					'is_upcoming'  => false,
					'demo_url'     => '',
					'doc_url'      => 'https://support.wpdesignbox.com/docs/wdb/advanced-settings/advanced-settings/wdb-custom-css/',
					'youtube_url'  => '',
				],
				'popup'      => [
					'label'        => esc_html__( 'Popup', 'designbox-builder' ),
					'is_pro'       => false,
					'is_extension' => true,
					'is_upcoming'  => false,
					'demo_url'     => '',
					'doc_url'      => 'https://support.wpdesignbox.com/docs/wdb/advanced-settings/advanced-settings/wdb-popup/',
					'youtube_url'  => '',
				],
			]
		],
		'gsap-extensions'    => [
			'title'    => __( 'Gsap Extension', 'designbox-builder' ),
			'elements' => [
				'animation-effects'       => [
					'label'        => esc_html__( 'Animation', 'designbox-builder' ),
					'is_pro'       => false,
					'is_extension' => true,
					'is_upcoming'  => false,
					'demo_url'     => '',
					'doc_url'      => 'https://support.wpdesignbox.com/docs/wdb/advanced-settings/advanced-settings/wdb-animation/',
					'youtube_url'  => '',
				],
				'pin-element'             => [
					'label'        => esc_html__( 'Pin Element', 'designbox-builder' ),
					'is_pro'       => false,
					'is_extension' => true,
					'is_upcoming'  => false,
					'demo_url'     => '',
					'doc_url'      => 'https://support.wpdesignbox.com/docs/wdb/advanced-settings/advanced-settings/pin-element/',
					'youtube_url'  => '',
				],
				'text-animation-effects'  => [
					'label'        => esc_html__( 'Text Animation', 'designbox-builder' ),
					'is_pro'       => false,
					'is_extension' => true,
					'is_upcoming'  => false,
					'demo_url'     => '',
					'doc_url'      => 'https://support.wpdesignbox.com/docs/wdb/animation/animation/text-animation/',
					'youtube_url'  => '',
				],
				'image-animation-effects' => [
					'label'        => esc_html__( 'Image Animation', 'designbox-builder' ),
					'is_pro'       => false,
					'is_extension' => true,
					'is_upcoming'  => false,
					'demo_url'     => '',
					'doc_url'      => 'https://support.wpdesignbox.com/docs/wdb/animation/animation/image-animation/',
					'youtube_url'  => '',
				],
			]
		],
	],
];

$GLOBALS['wdb_addons_config'] = $config;
